apiVersion: apps/v1
kind: Deployment
metadata:
  name: three
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uber
  template:
    metadata:
      labels:
        app: uber
    spec:
      containers:
      - name: cont-1
        image: kumar49/error:resource
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "NGINX APP2"
---
apiVersion: v1
kind: Service
metadata:
  name: uber
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: uber
